server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/csms
    username: postgres
    password: hetpatel
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

jwt:
  secret: IfiehPJUJeforh989y438y09902339h0

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
